services:
  - type: web
    name: sotnbus
    env: php
    repo: https://github.com/ezaputraandreanfallo1998-beep/sotnbus
    branch: main
    buildCommand: |
      composer install --no-dev
      php artisan key:generate
      php artisan migrate --force
    startCommand: php artisan serve --host=0.0.0.0 --port=10000
    envVars:
      - key: APP_NAME
        value: SOTNBUS
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://sotnbus.com
      - key: LOG_CHANNEL
        value: stack
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: 66fyrs.h.filess.io
      - key: DB_PORT
        value: 3307
      - key: DB_DATABASE
        value: sotnbus_cabindish
      - key: DB_USERNAME
        value: sotnbus_cabindish
      - key: DB_PASSWORD
        value: d417e6c485ca1f55793f827e12f114adcdcfc6eb
      - key: BROADCAST_DRIVER
        value: log
      - key: CACHE_DRIVER
        value: file
      - key: FILESYSTEM_DRIVER
        value: public
      - key: QUEUE_CONNECTION
        value: sync
      - key: SESSION_DRIVER
        value: file
      - key: SESSION_LIFETIME
        value: 120
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        value: mailpit
      - key: MAIL_PORT
        value: 1025
      - key: MAIL_USERNAME
        value: null
      - key: MAIL_PASSWORD
        value: null
      - key: MAIL_ENCRYPTION
        value: null
      - key: MAIL_FROM_ADDRESS
        value: noreply@sotnbus.com
      - key: MAIL_FROM_NAME
        value: SOTNBUS
      - key: VITE_APP_URL
        value: https://sotnbus.com
